services:
  - type: web
    name: ifix-experiment
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_PORT
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: GOOGLE_SHEETS_CLIENT_EMAIL
        sync: false
      - key: GOOGLE_SHEETS_PRIVATE_KEY
        sync: false
      - key: GOOGLE_SHEETS_ID
        sync: false
      - key: GOOGLE_PROJECT_ID
        sync: false
      - key: GOOGLE_PRIVATE_KEY_ID
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_SHEETS_RANGE
        sync: false
      - key: YOUTUBE_API_KEY
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: CLOUDINARY_FOLDER
        sync: false
